### ISSUE TITLE
Send all nominees eMail after 31st of July

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/awards#8]

**Comment by mariafanger** [comment]
Liebe/r

"" ist für die DINAcon Awards in der Kategorie ""  nominiert! Wir freuen uns sehr darüber, dieses spannende Projekt/Initiative in unseren Katalog nominierter Projekte aufzunehmen.

Um am 23. Oktober 2020 bei der Verleihung der DINAcon Awards dabei zu sein fehlt nur noch ein kleiner Schritt: kandidieren Sie für die Awards Verleihung in dem Sie über diesen Link Ihre Bewerbung vervollständigen: ""

Darin sind auch die bisher bei der Nomination angegebenen Informationen (durch Sie oder eine von Ihrem Projekt begeisterte Person) ersichtlich. Bearbeiten Sie diese schon ausgefüllten, sowie die noch erforderlichen Felder jetzt um an der diesjährigen DINAcon Konferenz für digitale Nachhaltigkeit in Bern für Ihr besonderes Engagement, Ihren Mut oder Ihre Innovationskraft im Bereich Open Source und Open Data ausgezeichnet zu werden.

Wir freuen uns auf Ihre Bewerbung und auf grossartige DINAcon Awards 2020!

Organisiert von der Forschungsstelle für digitale Nachhaltigkeit an der Universität Bern, dem Verein CH-Open, der parlamentarischen Gruppe Parldigi und weiteren Veranstaltern bringt die jährliche Konferenz Opinion Leaders und Interessierte aus Wirtschaft, Verwaltung und der Digitalisierungs-Szene zusammen. Kernthema dabei ist, wie Digitalisierung, Gesellschaft und Wirtschaft nachhaltig gestaltet werden können. 

Zur [Konferenzwebsite](https://dinacon.ch/)

Impressionen der letzten DINAcon Awards Verleihung [hier](https://awards.dinacon.ch/gewinner-2019/)

Beste Grüsse,

Markus Tiede und Maria Fanger, Organisatoren der DINAcon Awards

**Comment by MarkusTiede** [comment]
@mariafanger : Haben wir auch eine englische Version?

**Comment by mariafanger** [comment]
> @mariafanger : Haben wir auch eine englische Version?

@MarkusTiede noch nicht.. aber ich übersetze den text sonst noch gerade für die internationalen bewerber. :)

**Comment by mariafanger** [comment]
all emails sent out to the current entries :)  from now on informing ppl. right after they are nominated.

**Comment by mariafanger** [comment]
Dear 

" " is nominated for the DINAcon Awards in the category " Award"! We are very pleased to add this exciting project / initiative to our catalogue of nominated projects.
In order to be part of the DINAcon Awards on October 23rd, 2020, there is only one small step missing: apply for the Awards by completing your application via this link: ---

It also contains the information (by you or a person who is enthusiastic about your project) that has been given so far in the nomination. Please correct the already filled in fields and add to required information now to hopefully be honoured at this year's DINAcon Conference for Digital Sustainability in Bern for your special commitment, courage or innovative strength in the field of Open Source and Open Data.

We are looking forward to your application and to great DINAcon Awards 2020!

Organized by the Research Center for Digital Sustainability at the University of Bern, the CH-Open association, the parliamentary group Parldigi and other organizers, the annual conference brings together opinion leaders and interested parties from business, administration and the digitization scene. The core topic is how digitisation, society and economy can be shaped sustainably.
To the conference website
Impressions of the last DINAcon Awards  ceremony here

Best wishes,
Markus Tiede and Maria Fanger, organizers of the DINAcon Awards
